### ISSUE TITLE
Throws an error if pass a single word that contains a parenthesis

### ISSUE THREAD

**Issue by 2fd** [idauth/node-humanname#5]
```javascript

> humanname.parse('(Name)')

TypeError: Cannot read property 'split' of undefined
    at NameParse.safe_ucfirst (node_modules/humanname/lib/parse-names.js:156:18)
    at NameParse.fix_case (node_modules/humanname/lib/parse-names.js:144:12)
    at NameParse.parse (humanname/lib/parse-names.js:238:18)
    at repl:1:11
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:440:10)
    at emitOne (events.js:120:20)
```

**Comment by yubo56** [comment]
To add onto this,
```
> humanname.parse('Mr')
TypeError: Cannot read property 'split' of undefined
```
